### ISSUE TITLE
各位现在还能正常使用么？

### ISSUE THREAD

**Issue by haojiumeizhaoniliaotian** [linpingta/Lianjia-eroom-finder#5]
24.07.01 发现爬不了~~ http status 418

**Comment by naixidananhai** [comment]
我也是418错误，我把
def get_house_info(start_url, sess):
    html = sess.get(start_url).text
    # house_num = re.findall('共找到<span> (.*?) </span>套.*二手房', html)[0].strip()
    return 1000
这里改了下

**Comment by linpingta** [comment]
已fix，请拉取最新code @haojiumeizhaoniliaotian @naixidananhai
